2024-11-20 23:45:25,939 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Курсы\UrbanUniversity\homework\module12\tests_12_4.py", line 19, in test_run
    object = Runner(2, 5)
             ^^^^^^^^^^^^
  File "D:\Курсы\UrbanUniversity\homework\module12\module_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-20 23:45:25,940 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Курсы\UrbanUniversity\homework\module12\tests_12_4.py", line 9, in test_walk
    object = Runner('Вася', -5)
             ^^^^^^^^^^^^^^^^^^
  File "D:\Курсы\UrbanUniversity\homework\module12\module_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
